version: 2
jobs:
  lint-charts:
    docker:
      - image: quay.io/helmpack/chart-testing:v2.3.3
    steps:
      - checkout
      - run:
          name: Lint charts
          command: ct lint
workflows:
  version: 2
  lint:
    jobs:
      - lint-charts
